name: PR Checks

on:
  pull_request:
    branches: [master]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    outputs:
      node-version: ${{ steps.set.outputs.node-version }}
    steps:
      - id: set
        run: echo "node-version=20.x" >> $GITHUB_OUTPUT

  lint:
    needs: setup
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

  prettier:
    needs: setup
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Prettier Check
        run: npx prettier --check "**/*.{js,ts,tsx,json,css,md}" 
